name: activemq
on:
  push:
defaults:
  run:
    working-directory: activemq
jobs:
  localhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: davidkhala/mq
          path: mq
      - run: ./activeMQ/Docker/run.sh
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18.x
      - run: npm i
      - run: npm test
