name: kafka
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
defaults:
  run:
    working-directory: kafka
jobs:
  IBM:
    environment: IBMEventStreams
    env:
      api_key: ${{ secrets.API_KEY }}
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run IBM
  oracle:
    environment: OCIStreaming
    env:
      username: ${{ secrets.USERNAME }}
      authToken: ${{ secrets.AUTH_TOKEN }}
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run oracle
