name: mq
on:
  push:

jobs:
  activemq:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: activemq
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: |
          curl -sSL https://raw.githubusercontent.com/davidkhala/mq/main/activeMQ/docker-compose.yml > docker-compose.yml
          docker compose up -d
      - run: npm i
      - run: npm test
  rabbitmq:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rabbitmq
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: |
          curl -sSL https://raw.githubusercontent.com/davidkhala/mq/main/rabbitmq/docker-compose.yml > docker-compose.yml
          docker compose up -d
      - run: sleep 7
      - run: npm i
      - run: npm test