name: mq
on:
  push:

jobs:
  activemq:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: activemq
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: |
          curl -sSL https://raw.githubusercontent.com/davidkhala/mq/main/activeMQ/docker-compose.yml > docker-compose.yml
          docker compose up -d
      - run: npm i
      - run: npm test
  rabbitmq:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rabbitmq
    steps:
      - uses: davidkhala/setup-dockerode@main
      - run: |
          curl -sSL https://raw.githubusercontent.com/davidkhala/mq/main/rabbitmq/docker-compose.yml > docker-compose.yml
          docker compose up -d
      - run: sleep 15
      - run: npm i
      - run: npm test
  solace:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solace
    steps:
      - uses: actions/checkout@main
      - run: |
          curl -sSL https://raw.githubusercontent.com/davidkhala/mq/main/solace/docker-compose.yml > docker-compose.yml
          docker compose up -d
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - run: npm i
      - run: sleep 15
      - run: npm test